sudo: required
language: ruby
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script: bundle exec cucumber

before_script:
        - bundle install
        - brew tap homebrew/cask && brew cask install chromedriver

branches:
only:
- master

notifications:
  email:
    - bonifaciolivia@gmail.com
